version: '3'

services:
  ghost_blog:
    image: ghost:1-alpine
    restart: always
    ports:
    - 2368:2368
    depends_on:
      - 'mysql'
    environment:
      database_client: mysql
      database_connection_host: mysql
      database_connection_user: root
      database_connection_password: senharoot
      database_connection_database: ghost
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senharoot
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
